packages:
  - functions
overrides:
  storybook@>=9.0.0 <9.1.17: '>=9.1.17'
  storybook@>=8.7.0-alpha.0 <9.1.19: '>=9.1.19'
  '@tootallnate/once@<3.0.1': '>=3.0.1'
  ip-address@<=10.1.0: '>=10.1.1'
allowBuilds:
  '@firebase/util': true
  '@vaadin/vaadin-usage-statistics': true
  esbuild: true
  protobufjs: true
  re2: true
  unrs-resolver: false
